---
- hosts: Routers
  gather_facts: yes

  tasks:

  - name: Configuring BGP peer {{customer_peer_add}} - {{customer_desc}}
    ios_config:
      lines:
        - neighbor {{customer_peer_add}} remote-as {{customer_as}}
        - neighbor {{customer_peer_add}} description {{customer_desc}}-{{customer_circuit_id}}
        - neighbor {{customer_peer_add}} ebgp-multihop 5
        - neighbor {{customer_peer_add}} update-source Loopback100
        - address-family ipv4
        - neighbor {{customer_peer_add}} activate
        - neighbor {{customer_peer_add}} route-map {{customer_desc}}-AS{{customer_as}}-{{customer_circuit_id}}-V4-IN in
        - neighbor {{customer_peer_add}} route-map {{customer_desc}}-AS{{customer_as}}-{{customer_circuit_id}}-V4-OUT out
        - neighbor {{customer_peer_add}} maximum-prefix 250
      parents: router bgp 262596
