---
- name: Routers backup
  hosts: Routers
  gather_facts: false
   


  tasks:
    - name: Coleta data e hora
      command: date +%d%m%Y%H%M
      register: timestamp


    - name: Executa backup IOS-XR
      iosxr_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
          dir_path: /var/lib/awx/projects/cgrt-projects/files/backups/
      when: ansible_network_os == "iosxr"


    - name: Executa backup IOS
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}_{{ timestamp.stdout }}.txt"
          dir_path: /var/lib/awx/projects/cgrt-projects/files/backups/
      when: ansible_network_os == "ios"
